### ISSUE TITLE
Install doesn't check out master branches from submodules

### ISSUE THREAD

**Issue by voobscout** [senny/cabbage#225]
Most likely the issue is me not being fluent with git, so apologies for that first, but:

I noticed, that during install, cabbage checks out only specific commits from submodules into vendor/ dir, is there any reason for that?

And, can some gentle soul explain how to check out latest master from submodules during install?

**Comment by senny** [comment]
yes that's correct. Git submodules are locked in on a specific commit. They need to be updated manually. The reasoning behind submodules is that we wanted a very stable solution with cabbage. The Emacs environment has improved a lot in the last years but when we started it was quite tricky to install all the packages in versions which would work well together.

There is no easy way to install the latest version from all submodules. You need to `cd` into the submodule directory and do a `git checkout master && git pull`. Those updates can then be committed into the cabbage repository.

@voobscout are there specific packages you'd like to see a newer version or you'd like to generally be working with the cutting edge?

**Comment by voobscout** [comment]
It'd be pretty awesome to have an up2date magit, the version in cabbage is pretty old and has problems with latest magit-gitflow.

Actually, all other cutting edge works great, except for java and rails bundle. The workaround for me was melpa versions and commenting out bundles in config.el.

Dare I suggest updating cabbage bundles to current versions?

also, there's a nifty git command that'll update all the modules at once (as i have found out recently):

```bash
git submodule foreach "git checkout master && git pull"
```
It's probably ok to close this issue...

**Comment by senny** [comment]
If the versions are stable, there is no reason not to update.

@voobscout would you mind submitting a PR to update magit and other dependencies you see outdated? We'll run them for some time and decide wether it's working out or of if need to investigate issues.

**Comment by voobscout** [comment]
@senny PR submitted.
